kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prepuller
subjects:
- kind: ServiceAccount
  name: prepuller
  namespace: __NAMESPACE__
  apiGroup: ""
roleRef:
  kind: Role
  name: prepuller
  apiGroup: ""
