kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub
subjects:
- kind: ServiceAccount
  name: hub
  namespace: __NAMESPACE__
  apiGroup: ""
roleRef:
  kind: Role
  name: hub
  apiGroup: ""

