kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: __NAMESPACE__
  name: hub
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "watch", "delete"]
