---
apiVersion: v1
kind: Secret
metadata:
  name: hub
data:
  session_db_url: $(echo -n "${session_db_url}" | base64)
  jupyterhub_crypto_key: ${hub_crypto_key}
  # not used
  oauth_client_id: RU1QVFk=
  oauth_secret: RU1QVFk=
  oauth_callback_url: RU1QVFk=
  github_organization_whitelist: RU1QVFk=
  cilogon_group_whitelist: RU1QVFk=

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate
type: Opaque
data:
  cert.crt: $(cat ${hub_cert_file} | base64 -w 0)
  cert.key: $(cat ${hub_key_file} | base64 -w 0)
